compute_components_flag: false
config_ar: !!python/object:neuralprophet.configure.AR
  ar_reg: null
  n_lags: 0
  reg_lambda: null
config_events: null
config_holidays: null
config_lagged_regressors: null
config_normalization: !!python/object:neuralprophet.configure.Normalization
  global_data_params: !!python/object/apply:collections.OrderedDict
  - - - ds
      - &id002 !!python/object:neuralprophet.df_utils.ShiftScale
        scale: !!python/object/apply:pandas._libs.tslibs.timedeltas._timedelta_unpickle
        - 288162000000000000
        - 10
        shift: !!python/object/apply:pandas._libs.tslibs.timestamps._unpickle_timestamp
        - 1262304000000000000
        - null
        - null
        - 10
    - - y
      - !!python/object:neuralprophet.df_utils.ShiftScale
        scale: !!python/object/apply:numpy.core.multiarray.scalar
        - &id001 !!python/object/apply:numpy.dtype
          args:
          - f8
          - false
          - true
          state: !!python/tuple
          - 3
          - <
          - null
          - null
          - null
          - -1
          - -1
          - 0
        - !!binary |
          QArXoxDQt0A=
        shift: !!python/object/apply:numpy.core.multiarray.scalar
        - *id001
        - !!binary |
          hetRuF6d90A=
  global_normalization: true
  global_time_normalization: true
  local_data_params: !!python/object/apply:collections.OrderedDict
  - - - __df__
      - !!python/object/apply:collections.OrderedDict
        - - - ds
            - *id002
          - - y
            - !!python/object:neuralprophet.df_utils.ShiftScale
              scale: !!python/object/apply:numpy.core.multiarray.scalar
              - *id001
              - !!binary |
                QArXoxDQt0A=
              shift: !!python/object/apply:numpy.core.multiarray.scalar
              - *id001
              - !!binary |
                hetRuF6d90A=
  normalize: auto
  unknown_data_normalization: false
config_regressors: null
config_seasonality: !!python/object:neuralprophet.configure.ConfigSeasonality
  computation: fourier
  daily_arg: 10
  global_local: global
  mode: additive
  periods: !!python/object/apply:collections.OrderedDict
  - - - yearly
      - !!python/object:neuralprophet.configure.Season
        arg: 10
        period: 365.25
        resolution: 10
    - - daily
      - !!python/object:neuralprophet.configure.Season
        arg: 10
        period: 1
        resolution: 10
  reg_lambda: 0
  weekly_arg: false
  yearly_arg: 10
config_train: !!python/object:neuralprophet.configure.Train
  batch_size: 64
  epochs: 61
  lambda_delay: 30
  learning_rate: null
  loss_func: !!python/object:torch.nn.modules.loss.SmoothL1Loss
    _backward_hooks: !!python/object/apply:collections.OrderedDict
    - []
    _buffers: !!python/object/apply:collections.OrderedDict
    - []
    _forward_hooks: !!python/object/apply:collections.OrderedDict
    - []
    _forward_pre_hooks: !!python/object/apply:collections.OrderedDict
    - []
    _is_full_backward_hook: null
    _load_state_dict_post_hooks: !!python/object/apply:collections.OrderedDict
    - []
    _load_state_dict_pre_hooks: !!python/object/apply:collections.OrderedDict
    - []
    _modules: !!python/object/apply:collections.OrderedDict
    - []
    _non_persistent_buffers_set: !!set {}
    _parameters: !!python/object/apply:collections.OrderedDict
    - []
    _state_dict_hooks: !!python/object/apply:collections.OrderedDict
    - []
    beta: 1.0
    reduction: none
    training: true
  loss_func_name: SmoothL1Loss
  lr_finder_args: {}
  n_data: 80046
  newer_samples_start: 0.0
  newer_samples_weight: 2
  optimizer: !!python/name:torch.optim.adamw.AdamW ''
  optimizer_args:
    weight_decay: 0.001
  quantiles:
  - 0.5
  reg_delay_pct: 0.5
  reg_lambda_trend: null
  scheduler: !!python/name:torch.optim.lr_scheduler.OneCycleLR ''
  scheduler_args:
    anneal_strategy: cos
    div_factor: 100.0
    final_div_factor: 5000.0
    pct_start: 0.3
  trend_reg_threshold: false
config_trend: !!python/object:neuralprophet.configure.Trend
  changepoints: null
  changepoints_range: 0.95
  growth: linear
  n_changepoints: 50
  trend_global_local: global
  trend_reg: 0.001
  trend_reg_threshold: null
d_hidden: null
id_list:
- __df__
max_lags: 0
meta_used_in_model: false
metrics:
  MAE: !!python/object:torchmetrics.regression.mae.MeanAbsoluteError
    _backward_hooks: !!python/object/apply:collections.OrderedDict
    - []
    _buffers: !!python/object/apply:collections.OrderedDict
    - []
    _cache: null
    _computed: null
    _defaults:
      sum_abs_error: !!python/object/apply:torch._utils._rebuild_tensor_v2
      - !!python/object/apply:torch.storage._load_from_bytes
        - !!binary |
          gAKKCmz8nEb5IGqoUBkugAJN6QMugAJ9cQAoWBAAAABwcm90b2NvbF92ZXJzaW9ucQFN6QNYDQAA
          AGxpdHRsZV9lbmRpYW5xAohYCgAAAHR5cGVfc2l6ZXNxA31xBChYBQAAAHNob3J0cQVLAlgDAAAA
          aW50cQZLBFgEAAAAbG9uZ3EHSwR1dS6AAihYBwAAAHN0b3JhZ2VxAGN0b3JjaApGbG9hdFN0b3Jh
          Z2UKcQFYCwAAADEwODM0NzI0Njg4cQJYAwAAAGNwdXEDSwFOdHEEUS6AAl1xAFgLAAAAMTA4MzQ3
          MjQ2ODhxAWEuAQAAAAAAAAAAAAAA
      - 0
      - !!python/tuple []
      - !!python/tuple []
      - false
      - !!python/object/apply:collections.OrderedDict
        - []
      total: !!python/object/apply:torch._utils._rebuild_tensor_v2
      - !!python/object/apply:torch.storage._load_from_bytes
        - !!binary |
          gAKKCmz8nEb5IGqoUBkugAJN6QMugAJ9cQAoWBAAAABwcm90b2NvbF92ZXJzaW9ucQFN6QNYDQAA
          AGxpdHRsZV9lbmRpYW5xAohYCgAAAHR5cGVfc2l6ZXNxA31xBChYBQAAAHNob3J0cQVLAlgDAAAA
          aW50cQZLBFgEAAAAbG9uZ3EHSwR1dS6AAihYBwAAAHN0b3JhZ2VxAGN0b3JjaApMb25nU3RvcmFn
          ZQpxAVgLAAAAMTA5NzQ0NDYxNjBxAlgDAAAAY3B1cQNLAU50cQRRLoACXXEAWAsAAAAxMDk3NDQ0
          NjE2MHEBYS4BAAAAAAAAAAAAAAAAAAAA
      - 0
      - !!python/tuple []
      - !!python/tuple []
      - false
      - !!python/object/apply:collections.OrderedDict
        - []
    _device: !!python/object/apply:torch.device
    - cpu
    _enable_grad: false
    _forward_cache: !!python/object/apply:torch._utils._rebuild_tensor_v2
    - !!python/object/apply:torch.storage._load_from_bytes
      - !!binary |
        gAKKCmz8nEb5IGqoUBkugAJN6QMugAJ9cQAoWBAAAABwcm90b2NvbF92ZXJzaW9ucQFN6QNYDQAA
        AGxpdHRsZV9lbmRpYW5xAohYCgAAAHR5cGVfc2l6ZXNxA31xBChYBQAAAHNob3J0cQVLAlgDAAAA
        aW50cQZLBFgEAAAAbG9uZ3EHSwR1dS6AAihYBwAAAHN0b3JhZ2VxAGN0b3JjaApGbG9hdFN0b3Jh
        Z2UKcQFYCwAAADExNzM1MzM4NTYwcQJYAwAAAGNwdXEDSwFOdHEEUS6AAl1xAFgLAAAAMTE3MzUz
        Mzg1NjBxAWEuAQAAAAAAAACmu/Y/
    - 0
    - !!python/tuple []
    - !!python/tuple []
    - false
    - !!python/object/apply:collections.OrderedDict
      - []
    _forward_hooks: !!python/object/apply:collections.OrderedDict
    - []
    _forward_pre_hooks: !!python/object/apply:collections.OrderedDict
    - []
    _is_full_backward_hook: null
    _is_synced: false
    _load_state_dict_post_hooks: !!python/object/apply:collections.OrderedDict
    - []
    _load_state_dict_pre_hooks: !!python/object/apply:collections.OrderedDict
    - []
    _modules: !!python/object/apply:collections.OrderedDict
    - []
    _non_persistent_buffers_set: !!set {}
    _parameters: !!python/object/apply:collections.OrderedDict
    - []
    _persistent:
      sum_abs_error: false
      total: false
    _reductions:
      sum_abs_error: &id003 !!python/name:torchmetrics.utilities.data.dim_zero_sum ''
      total: *id003
    _should_unsync: true
    _state_dict_hooks: !!python/object/apply:collections.OrderedDict
    - []
    _to_sync: true
    _update_count: 155606
    compute_on_cpu: false
    dist_sync_fn: null
    dist_sync_on_step: false
    process_group: null
    sum_abs_error: !!python/object/apply:torch._utils._rebuild_tensor_v2
    - !!python/object/apply:torch.storage._load_from_bytes
      - !!binary |
        gAKKCmz8nEb5IGqoUBkugAJN6QMugAJ9cQAoWBAAAABwcm90b2NvbF92ZXJzaW9ucQFN6QNYDQAA
        AGxpdHRsZV9lbmRpYW5xAohYCgAAAHR5cGVfc2l6ZXNxA31xBChYBQAAAHNob3J0cQVLAlgDAAAA
        aW50cQZLBFgEAAAAbG9uZ3EHSwR1dS6AAihYBwAAAHN0b3JhZ2VxAGN0b3JjaApGbG9hdFN0b3Jh
        Z2UKcQFYCwAAADExMjc0ODIwMjcycQJYAwAAAGNwdXEDSwFOdHEEUS6AAl1xAFgLAAAAMTEyNzQ4
        MjAyNzJxAWEuAQAAAAAAAADie/lL
    - 0
    - !!python/tuple []
    - !!python/tuple []
    - false
    - !!python/object/apply:collections.OrderedDict
      - []
    sync_on_compute: true
    total: !!python/object/apply:torch._utils._rebuild_tensor_v2
    - !!python/object/apply:torch.storage._load_from_bytes
      - !!binary |
        gAKKCmz8nEb5IGqoUBkugAJN6QMugAJ9cQAoWBAAAABwcm90b2NvbF92ZXJzaW9ucQFN6QNYDQAA
        AGxpdHRsZV9lbmRpYW5xAohYCgAAAHR5cGVfc2l6ZXNxA31xBChYBQAAAHNob3J0cQVLAlgDAAAA
        aW50cQZLBFgEAAAAbG9uZ3EHSwR1dS6AAihYBwAAAHN0b3JhZ2VxAGN0b3JjaApMb25nU3RvcmFn
        ZQpxAVgLAAAAMTA4NTYzNjk3MTJxAlgDAAAAY3B1cQNLAU50cQRRLoACXXEAWAsAAAAxMDg1NjM2
        OTcxMnEBYS4BAAAAAAAAAGrLugAAAAAA
    - 0
    - !!python/tuple []
    - !!python/tuple []
    - false
    - !!python/object/apply:collections.OrderedDict
      - []
    training: false
  RMSE: !!python/object:torchmetrics.regression.mse.MeanSquaredError
    _backward_hooks: !!python/object/apply:collections.OrderedDict
    - []
    _buffers: !!python/object/apply:collections.OrderedDict
    - []
    _cache: null
    _computed: null
    _defaults:
      sum_squared_error: !!python/object/apply:torch._utils._rebuild_tensor_v2
      - !!python/object/apply:torch.storage._load_from_bytes
        - !!binary |
          gAKKCmz8nEb5IGqoUBkugAJN6QMugAJ9cQAoWBAAAABwcm90b2NvbF92ZXJzaW9ucQFN6QNYDQAA
          AGxpdHRsZV9lbmRpYW5xAohYCgAAAHR5cGVfc2l6ZXNxA31xBChYBQAAAHNob3J0cQVLAlgDAAAA
          aW50cQZLBFgEAAAAbG9uZ3EHSwR1dS6AAihYBwAAAHN0b3JhZ2VxAGN0b3JjaApGbG9hdFN0b3Jh
          Z2UKcQFYCwAAADExNzM1MzkzMzQ0cQJYAwAAAGNwdXEDSwFOdHEEUS6AAl1xAFgLAAAAMTE3MzUz
          OTMzNDRxAWEuAQAAAAAAAAAAAAAA
      - 0
      - !!python/tuple []
      - !!python/tuple []
      - false
      - !!python/object/apply:collections.OrderedDict
        - []
      total: !!python/object/apply:torch._utils._rebuild_tensor_v2
      - !!python/object/apply:torch.storage._load_from_bytes
        - !!binary |
          gAKKCmz8nEb5IGqoUBkugAJN6QMugAJ9cQAoWBAAAABwcm90b2NvbF92ZXJzaW9ucQFN6QNYDQAA
          AGxpdHRsZV9lbmRpYW5xAohYCgAAAHR5cGVfc2l6ZXNxA31xBChYBQAAAHNob3J0cQVLAlgDAAAA
          aW50cQZLBFgEAAAAbG9uZ3EHSwR1dS6AAihYBwAAAHN0b3JhZ2VxAGN0b3JjaApMb25nU3RvcmFn
          ZQpxAVgLAAAAMTE3MzUzODcxMzZxAlgDAAAAY3B1cQNLAU50cQRRLoACXXEAWAsAAAAxMTczNTM4
          NzEzNnEBYS4BAAAAAAAAAAAAAAAAAAAA
      - 0
      - !!python/tuple []
      - !!python/tuple []
      - false
      - !!python/object/apply:collections.OrderedDict
        - []
    _device: !!python/object/apply:torch.device
    - cpu
    _enable_grad: false
    _forward_cache: !!python/object/apply:torch._utils._rebuild_tensor_v2
    - !!python/object/apply:torch.storage._load_from_bytes
      - !!binary |
        gAKKCmz8nEb5IGqoUBkugAJN6QMugAJ9cQAoWBAAAABwcm90b2NvbF92ZXJzaW9ucQFN6QNYDQAA
        AGxpdHRsZV9lbmRpYW5xAohYCgAAAHR5cGVfc2l6ZXNxA31xBChYBQAAAHNob3J0cQVLAlgDAAAA
        aW50cQZLBFgEAAAAbG9uZ3EHSwR1dS6AAihYBwAAAHN0b3JhZ2VxAGN0b3JjaApGbG9hdFN0b3Jh
        Z2UKcQFYCwAAADExMjc0ODEzNTg0cQJYAwAAAGNwdXEDSwFOdHEEUS6AAl1xAFgLAAAAMTEyNzQ4
        MTM1ODRxAWEuAQAAAAAAAAB7LBxA
    - 0
    - !!python/tuple []
    - !!python/tuple []
    - false
    - !!python/object/apply:collections.OrderedDict
      - []
    _forward_hooks: !!python/object/apply:collections.OrderedDict
    - []
    _forward_pre_hooks: !!python/object/apply:collections.OrderedDict
    - []
    _is_full_backward_hook: null
    _is_synced: false
    _load_state_dict_post_hooks: !!python/object/apply:collections.OrderedDict
    - []
    _load_state_dict_pre_hooks: !!python/object/apply:collections.OrderedDict
    - []
    _modules: !!python/object/apply:collections.OrderedDict
    - []
    _non_persistent_buffers_set: !!set {}
    _parameters: !!python/object/apply:collections.OrderedDict
    - []
    _persistent:
      sum_squared_error: false
      total: false
    _reductions:
      sum_squared_error: *id003
      total: *id003
    _should_unsync: true
    _state_dict_hooks: !!python/object/apply:collections.OrderedDict
    - []
    _to_sync: true
    _update_count: 155606
    compute_on_cpu: false
    dist_sync_fn: null
    dist_sync_on_step: false
    process_group: null
    squared: false
    sum_squared_error: !!python/object/apply:torch._utils._rebuild_tensor_v2
    - !!python/object/apply:torch.storage._load_from_bytes
      - !!binary |
        gAKKCmz8nEb5IGqoUBkugAJN6QMugAJ9cQAoWBAAAABwcm90b2NvbF92ZXJzaW9ucQFN6QNYDQAA
        AGxpdHRsZV9lbmRpYW5xAohYCgAAAHR5cGVfc2l6ZXNxA31xBChYBQAAAHNob3J0cQVLAlgDAAAA
        aW50cQZLBFgEAAAAbG9uZ3EHSwR1dS6AAihYBwAAAHN0b3JhZ2VxAGN0b3JjaApGbG9hdFN0b3Jh
        Z2UKcQFYCgAAADY0NDIzMTg1MTJxAlgDAAAAY3B1cQNLAU50cQRRLoACXXEAWAoAAAA2NDQyMzE4
        NTEycQFhLgEAAAAAAAAASOltTQ==
    - 0
    - !!python/tuple []
    - !!python/tuple []
    - false
    - !!python/object/apply:collections.OrderedDict
      - []
    sync_on_compute: true
    total: !!python/object/apply:torch._utils._rebuild_tensor_v2
    - !!python/object/apply:torch.storage._load_from_bytes
      - !!binary |
        gAKKCmz8nEb5IGqoUBkugAJN6QMugAJ9cQAoWBAAAABwcm90b2NvbF92ZXJzaW9ucQFN6QNYDQAA
        AGxpdHRsZV9lbmRpYW5xAohYCgAAAHR5cGVfc2l6ZXNxA31xBChYBQAAAHNob3J0cQVLAlgDAAAA
        aW50cQZLBFgEAAAAbG9uZ3EHSwR1dS6AAihYBwAAAHN0b3JhZ2VxAGN0b3JjaApMb25nU3RvcmFn
        ZQpxAVgLAAAAMTE3MzUzNTU2NjRxAlgDAAAAY3B1cQNLAU50cQRRLoACXXEAWAsAAAAxMTczNTM1
        NTY2NHEBYS4BAAAAAAAAAGrLugAAAAAA
    - 0
    - !!python/tuple []
    - !!python/tuple []
    - false
    - !!python/object/apply:collections.OrderedDict
      - []
    training: false
n_forecasts: 1
n_lags: 0
num_hidden_layers: 0
num_seasonalities_modelled: 1
num_trends_modelled: 1
